version: "3.8"

networks:
  demet:
    driver: bridge

services:
  webserver:
    build:
      context: ./docker/nginx
      args:
        - PHP_CONTAINER=php83
    image: demet-webserver
    container_name: frontendcmon
    restart: always
    environment:
      - PHP_CONTAINER=php83
    networks:
      - demet
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./public:/var/www/html
      - ./logs/webserver:/var/log/nginx
    depends_on:
      - php83

  php83:
    build:
      context: ./docker/php83
    image: demet-php
    container_name: php83
    restart: always
    networks:
      - demet
    environment:
      TZ: Asia/Bangkok
    volumes:
      - ./public:/var/www/html


###
#  docker compose up --build -d  
#  docker ps               
#  docker-compose down
#  docker-compose up --build
#  /home/cmon/Public/appcmon
#  sudo chown -R $USER:$USER ${DEMET_PATH}/public

